#!/bin/bash

for f in $(git ls-files '*.c')
do
    OBJ=$(echo $f: | sed 's=\.c=.o=')
    DEPS=$(cc -E $f | awk '$3 ~ /^"\.\/.*\.h"$/ {print $3}' |
	    sed -e 's=^"./==' -e 's="$==' | sort -u)
    echo $OBJ $DEPS
done
